$(function(){
	
	$("#signupForm1").validate({
		rules:{
			phone:{
				required:true,
				number:true,
				minlength:11,
				maxlength:11
			},
			code:{
				required:true,
				minlength:6
			},
			password:{
				required:true,
				number:true,
				rangelength:[6,16]
			},
			agree:"required",	
		},
		messages:{
			phone:{
				required:"请输入手机号码",
				number:"格式不正确",
				minlength:"手机号码不正确，不能少于11个字符",
				maxlength:"手机号码不正确，不能超过11个字符"
			},
			code:{
				required:"请输入验证码",
				minlength:"验证码不符合要求"
			},
			password:{
				required:"请输入密码",
				number:"密码只能是数字类型",
				rangelength:"请输入6-16位数字"
			},
			
			agree:"请确认已阅读并同意Flyme服务协议条款",
		},
		errorPlacement:function(error,element){
			error.appendTo(element.parent().next()); 
		},
		errorClass:"myerror"
	})

	$("#signupForm2").validate({
		rules:{
			username:{
				required:true,
				rangelength:[4,32]
			},
			password:{
				required:true,
				rangelength:[8,16]
			},
			email:{
				required:true,
				email:true
			},
			code:{
				required:true,
				minlength:6
			},
			
			agree:"required",	
		},
		messages:{
			username:{
				required:"请写账号",
				rangelength:"账号长度不对，需输入4-32位"
			},
			password:{
				required:"密码不能为空",
				rangelength:"密码应为8-16个字符，区分大小写请输入8-16位数字"
			},
			email:{
				required:"邮箱不能为空",
				email:"邮箱格式不正确"
			},
			code:{
				required:"请输入验证码",
				minlength:"验证码不符合要求"
			},
			agree:"请确认已阅读并同意Flyme服务协议条款",
		},
		errorPlacement:function(error,element){
			error.appendTo(element.parent().next()); 
		},
		errorClass:"myerror"
	})
	
})